"""Report generation: JSON aggregates, a PDF monthly summary and a GST-ready
demo CSV export. Kept dependency-light (reportlab + stdlib csv only)."""
from __future__ import annotations

import csv
import io


def monthly_report_data(business_name: str, period_label: str, transactions: list[dict]) -> dict:
    total_income = sum(float(t['amount']) for t in transactions if t['type'] == 'income')
    total_expenses = sum(float(t['amount']) for t in transactions if t['type'] == 'expense')

    by_category: dict[str, float] = {}
    for t in transactions:
        if t['type'] != 'expense':
            continue
        cat = t.get('category') or 'Other'
        by_category[cat] = by_category.get(cat, 0.0) + float(t['amount'])

    by_vendor: dict[str, float] = {}
    for t in transactions:
        vendor = t.get('vendor') or 'Unknown'
        by_vendor[vendor] = by_vendor.get(vendor, 0.0) + float(t['amount'])

    return {
        'business_name': business_name,
        'period': period_label,
        'total_income': round(total_income, 2),
        'total_expenses': round(total_expenses, 2),
        'net_cash_flow': round(total_income - total_expenses, 2),
        'category_breakdown': [
            {'category': k, 'amount': round(v, 2)} for k, v in sorted(by_category.items(), key=lambda x: -x[1])
        ],
        'vendor_summary': [
            {'vendor': k, 'amount': round(v, 2)} for k, v in sorted(by_vendor.items(), key=lambda x: -x[1])
        ],
        'transaction_count': len(transactions),
    }


def build_monthly_pdf(report: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(report['business_name'], styles['Title']))
    story.append(Paragraph(f"Monthly Financial Report — {report['period']}", styles['Heading2']))
    story.append(Spacer(1, 10))

    summary_rows = [
        ['Total Income', f"₹{report['total_income']:,.2f}"],
        ['Total Expenses', f"₹{report['total_expenses']:,.2f}"],
        ['Net Cash Flow', f"₹{report['net_cash_flow']:,.2f}"],
        ['Transactions', str(report['transaction_count'])],
    ]
    summary_table = Table(summary_rows, colWidths=[200, 200])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecfdf5')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#065f46')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph('Category Breakdown', styles['Heading3']))
    cat_rows = [['Category', 'Amount']] + [
        [c['category'], f"₹{c['amount']:,.2f}"] for c in report['category_breakdown']
    ] or [['-', '-']]
    cat_table = Table(cat_rows, colWidths=[260, 140])
    cat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(cat_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph('Vendor Summary', styles['Heading3']))
    vendor_rows = [['Vendor', 'Amount']] + [
        [v['vendor'], f"₹{v['amount']:,.2f}"] for v in report['vendor_summary'][:15]
    ] or [['-', '-']]
    vendor_table = Table(vendor_rows, colWidths=[260, 140])
    vendor_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(vendor_table)
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        'Generated by DHAN — prototype financial management platform for MSMEs.',
        styles['Normal'],
    ))

    doc.build(story)
    return buffer.getvalue()


GST_EXPORT_HEADER = [
    'Date', 'Type', 'Description', 'Category', 'Vendor', 'Amount (INR)',
    'Payment Method', 'GST Number', 'Note',
]


def build_gst_export_csv(business_gstin: str | None, transactions: list[dict]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(['GST-ready demo export — not an officially validated GST filing format'])
    writer.writerow(['Business GSTIN', business_gstin or 'Not set'])
    writer.writerow([])
    writer.writerow(GST_EXPORT_HEADER)
    for t in transactions:
        writer.writerow([
            str(t.get('date') or ''),
            t.get('type', ''),
            t.get('description', ''),
            t.get('category') or '',
            t.get('vendor') or '',
            f"{float(t.get('amount') or 0):.2f}",
            t.get('payment_method', ''),
            business_gstin or '',
            'Demo export',
        ])
    return buffer.getvalue()
